user_rpc:
  ip: 0.0.0.0
  port: 10051
log:
  app: shop_service
  dir: logs
db:
  user: root
  password: root
  host: 127.0.0.1
  port: 3306
  db: user-srv
  debug: false
  source: mysql

consul_info:
  port: 8500
  addr: 192.168.163.50
  name: user_service

local_info:
  port: 10051
  addr: 192.168.163.1