nacos_info:
  host: "192.168.163.132"
  port: 8848
  user: nacos
  password: nacos
  data_id: oss_web_dev.yaml
  group: dev
  namespace: 605725ee-1cc0-4e9e-884d-83f6f304852b
  access_token: S1wVNXtCe2HraKU6GsAsYPq5Zaux9b0KLfZgMhZbRbk=

