system:
  ip: 0.0.0.0
  port: 8080
  env: dev
  gin_mode: release
log:
  app: shop_service
  dir: logs
db:
  user: root
  password: root
  host: 127.0.0.1
  port: 3306
  db: user-srv
  debug: false
  source: mysql

user_rpc:
  ip: 0.0.0.0
  port: 10051