nacos_info:
  host: "192.168.163.132"
  port: 8848
  user: nacos
  password: nacos
  data_id: goods_service_dev.yaml
  group: dev
  namespace: S1wVNXtCe2HraKU6GsAsYPq5Zaux9b0KLfZgMhZbRbk
  access_token: S1wVNXtCe2HraKU6GsAsYPq5Zaux9b0KLfZgMhZbRbk=

