nacos_info:
  host: "192.168.163.50"
  port: 8848
  user: nacos
  password: nacos
  data_id: goods_service_dev.yaml
  group: dev
  namespace: 04e78919-1fdc-4038-a29a-821bad0cb310
  access_token: S1wVNXtCe2HraKU6GsAsYPq5Zaux9b0KLfZgMhZbRbk=

