nacos_info:
  host: "192.168.163.50"
  port: 8848
  user: nacos
  password: nacos
  data_id: use_service_dev.yaml
  group: dev
  namespace: b5dc39e2-0639-4fbc-a591-d84a0903381a
  access_token: S1wVNXtCe2HraKU6GsAsYPq5Zaux9b0KLfZgMhZbRbk=


db:
  user: root
  password: root
  host: 127.0.0.1
  port: 3306
  db: good-srv
  debug: false
  source: mysql

consul_info:
  port: 8500
  addr: 192.168.163.50
  name: goods_service

local_info:
  addr: 192.168.163.1